### ISSUE TITLE
Too many branches

### ISSUE THREAD

**Issue by ye-luo** [USCCACS/RXMD#29]
A year ago 10 branches, now 28. This is a development process (human) bug.

We should adopt best development practices.
Every developer needs to use a fork and work under their fork.
If a feature is ready and well tested, it needs a pull request and a proper code review before merging.
The master must be protected such that no one can push directly.
A not merged feature basically doesn't exist so once done, must be merged or dropped in the developer fork.

**Comment by naromero77** [comment]
This is the workflow we use for QMCPACK development. Hopefully it is helpful to you as well.
https://github.com/QMCPACK/qmcpack/wiki/Development-workflow

**Comment by KenichiNomura** [comment]
not completely cleaned up but deleted some unused branches.
