### ISSUE TITLE
Code refactoring: variable names are not descriptive.

### ISSUE THREAD

**Issue by kuangluvasuka** [USCCACS/RXMD#30]
We should use elegant naming rules to improve readability.

**Comment by KenichiNomura** [comment]
we all should read this book! 
https://www.amazon.com/Art-Readable-Code-Practical-Techniques-ebook/dp/B0064CZ1XE

**Comment by TaufeqRazakh** [comment]
Wonderful book reference, since our scientific code is correctness and we are making progress everyday I am going to close this issue.
