### ISSUE TITLE
Newest PR breaks gfortran's max line length

### ISSUE THREAD

**Issue by georgevanderson** [USCCACS/RXMD#42]
This throws an error during compilation with gfortran. IFORT standard accepts more characters per line which is probably why no error was caught.  Putting an "&" in the line to break it up fixes the compilation issue. I would PR but I don't know how you like to style things.

https://github.com/USCCACS/RXMD/commit/f1921e3f0c494a1a33913339056b3a595909fc55#diff-37d96c124895d5e497ec69cc1bc50894R248

**Comment by KenichiNomura** [comment]
Thank you for catching it, georgevanderson! I've pushed my fix to master.
