### ISSUE TITLE
hello ,I have made a xyz file like yours, but when I build the geometry following your manual, I have this error below, I can't find what's wrong

### ISSUE THREAD

**Issue by junjinxiao** [USCCACS/RXMD#43]

**Comment by junjinxiao** [comment]
forrtl: severe (59): list-directed I/O syntax error, unit 1, file /gpfs/home/zhzhang/jxiao/software/rxmd/init/input.xyz
Image              PC                Routine            Line        Source
geninit            000000000040B3FE  Unknown               Unknown  Unknown
geninit            000000000042A59D  Unknown               Unknown  Unknown
geninit            00000000004285FE  Unknown               Unknown  Unknown
geninit            0000000000403AEB  Unknown               Unknown  Unknown
geninit            00000000004025DE  Unknown               Unknown  Unknown
libc.so.6          00002B27DC9243D5  Unknown               Unknown  Unknown
geninit            00000000004024E9  Unknown               Unknown  Unknown
make: *** [geninit] Error 59

**Comment by junjinxiao** [comment]
_8000
82.4000 82.4000 82.4000 90.000 90.000 90.000
C   0.417584951 0.048143204 0.232827670
C   0.405133495 0.059720874 0.225279126
C   0.407111650 0.060546117 0.206808252
C   0.394004854 0.071383495 0.199271845
H   0.416152913 0.035873786 0.227415049
H   0.430036408 0.052584951 0.230109223
H   0.392682039 0.055497573 0.228264563
H   0.406783981 0.072075243 0.230473301
H   0.419332524 0.065485437 0.203883495_

**Comment by sctiwari** [comment]
Please add any comment next to total number of atom. Currently, it is required as part of the input file

**Comment by junjinxiao** [comment]
aha,wow. thank you very much，I can 't find it without yourhelp

**Comment by junjinxiao** [comment]
could you tell me how do you build the xyz file,? I often build it from material studio, but sometimes when I run it in 100 steps. It just give me the information below , and no other output information
The output (if any) follows:

              _rxmd has started
------------------------------------------------------------
       ReaxFF parms have been read from               ffield
 Header :                Reactive MD-force field: nitramines (RDX/HMX/TATB/PETN)
  C - 1,   H - 2,   O - 3,   N - 4,   S - 5,  Si - 6,   X - 7,
------------------------------------------------------------
----------------------------------------------------------------
         req/alloc # of procs:       27  /       27
         req proc arrengement:        3        3        3
                parameter set:Reactive MD-force field: nitramines (RDX/HMX/TATB/PETN)
                time step[fs]:    1.00E-01
 MDMODE CURRENTSTEP NTIMESTPE:  1         0       100
  isQEq,QEq_tol,NMAXQEq,qstep:     1   1.0E-07   500     1
                Lex_fqs,Lex_k:   1.000   2.000
            treq,vsfact,sstep:    2500.000   1.000      100
                  fstep,pstep:   100    10
               NATOMS GNATOMS:                     402                   10000
                         LBOX:       0.333       0.333       0.333
                  Hmatrix [A]:         91.736          0.000          0.000
                  Hmatrix [A]:          0.000         90.736          0.000
                  Hmatrix [A]:          0.000          0.000         90.736
               lata,latb,latc:      91.736      90.736      90.736
          lalpha,lbeta,lgamma:      90.000      90.000      90.000
               density [g/cc]:    0.2555
         # of linkedlist cell:     9     9     9
            maxrc, lcsize [A]:     3.150        3.40      3.36      3.36
    # of linkedlist cell (NB):    10    10    10
              lcsize [A] (NB):      3.06      3.02      3.02
     MAXNEIGHBS, MAXNEIGHBS10:    30  1500
            NMINCELL, NBUFFER:     4    30000
    FFPath, DataDir, ParmPath:      ffield          DAT      rxmd.in
          # of atoms per type:        1200 - 1        2600 - 2        6200 - 3
----------------------------------------------------------------
nstep  TE  PE  KE: 1-Ebond 2-(Elnpr,Eover,Eunder) 3-(Eval,Epen,Ecoa) 4-(Etors,Econj) 5-Ehbond 6-(Evdw,EClmb,Echarge)_

**Comment by sctiwari** [comment]
Please attach your initial system to debug. It is impossible to look at just system error and debug.
